# -*- coding: utf-8 -*-
"""LangGraphArchitecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h71SizaqMrE640Jpv73CgDps5MysOo2o

#⚙️​ 모델 로드

tool calling을 위한 래핑 필요 - 챗지피티 대화 참고
"""

#모델 로드 초기화
import torch
import gc

# (Jupyter Notebook 환경에서 모델 객체 삭제하던 부분 스크립트화 시 에러로 주석처리)
# del model
# 가비지 컬렉션 강제 실행
gc.collect()

# GPU 캐시 비우기 (PyTorch 사용 시)
torch.cuda.empty_cache()

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

#모델로드 기본옵션 - 큐웬용

MODEL_NAME = "Qwen/Qwen2.5-14B-Instruct"
#MODEL_NAME = "Qwen/Qwen2.5-32B-Instruct"
#MODEL_NAME = "Qwen/Qwen2.5-72B-Instruct"
#MODEL_NAME = "google/gemma-3-27b-it"
#MODEL_NAME = "openai/gpt-oss-20b"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,  #플롯 앞에 b추가
    device_map="auto",
    trust_remote_code=True
)

model.eval()


"""# 🧾 데이터 스키마"""

from typing import List, TypedDict, Literal
from decimal import Decimal
from enum import Enum

# 1. 중복적용이 가능한 질병 정보
class DiseaseInfo(TypedDict):
    group: str           # 4개 군 이름 (예: 'Allergy', 'Diabetes', 'Hypertension', 'Kidney disorder' 등)
    step: int            # 세부 단계 (예: 1, 2, 3)
    description: str     # 해당 단계에 대한 간략한 설명 (선택 사항)

# 2. 메인 클래스 (State)
class overallState(TypedDict):
    user_id: str
    product_id: str
    name: str

    # [User-Agent가 채워줄 정보]
    diabetes_flag: int
    hypertension_flag: int
    kidneydisease_flag: int
    allergy_flag: int

    diabetes_detail: Literal["DIABETES"] | None #"TYPE_1", "TYPE_2", "GESTATIONAL"
    hypertension_detail: Literal["HYPERTENSION"] | None #"STAGE_1", "STAGE_2"
    kidney_detail: Literal["CKD_3_5", "HD", "PD"] | None
    allergy_list: List[str]

    #guidelines: List[str]
    final_profile: dict

    # [chat-Agent가 채워줄 정보]
    any_exceed : bool
    exceeded_nutrients: List[str]

    any_allergen: bool          # 제품에 알러지 유발 물질이 포함되었는가?
    substitute: List[str]      # 추천 대체 식재료 목록


    allergy_safety_summary: str
    warniing : bool

    # [흐름 제어]
    next_step: str
    final_answer: str              # 사용자에게 보여줄 최종 답변



class KFDAAllergen(str, Enum):
    """식약처 고시 알레르기 유발물질 22종"""
    EGG = "난류(가금류)"
    MILK = "우유"
    BUCKWHEAT = "메밀"
    PEANUT = "땅콩"
    SOYBEAN = "대두"
    WHEAT = "밀"
    MACKEREL = "고등어"
    CRAB = "게"
    SHRIMP = "새우"
    PORK = "돼지고기"
    PEACH = "복숭아"
    TOMATO = "토마토"
    SULFITE = "아황산류"
    WALNUT = "호두"
    CHICKEN = "닭고기"
    BEEF = "쇠고기"
    SQUID = "오징어"
    SHELLFISH = "조개류(굴, 전복, 홍합 포함)"
    PINE_NUT = "잣"
    # ... (나머지 포함 총 22종)

# 파이널 프로필 생성 메서드
# LangGraph 실행단에서는 DB에 저장되어 있음을 가정함
# final_profile: dict

def generate_final_profile(user_id, user_diseases, user_weight):
    # 1. 질환별 임계값 설정 (Data Dictionary)
    # 수치 뒤의 'g', 'mg' 등의 단위는 계산 편의를 위해 생략합니다.
    disease_thresholds = {
        "allergy": {
            "restricted_ingredients": ["milk", "egg", "peanut", "nuts", "soy", "wheat", "fish", "shellfish"]
        },
        "kidneydisease_pre_dialysis": {  # CKD 3-5단계 (투석 전)
            "protein": 0.20 * user_weight, # kg당 계산 (1일 기준: 0.60 * user_weight)
            "sodium": 766.67,              # 1일 기준: 2300
            "phosphorus": 333.33,          # 1일 기준: 1000
            "calcium": 333.33              # 1일 기준: 1000
        },
        "kidneydisease_dialysis": {      # CKD 5단계 (투석)
            "protein": 0.40 * user_weight, # kg당 계산 (1일 기준: 1.2 * user_weight)
            "sodium": 766.67,              # 1일 기준: 2300
            "potassium": 666.67,           # 1일 기준: 2000
            "phosphorus": 333.33,          # 1일 기준: 1000
            "calcium": 333.33              # 1일 기준: 1000
        },
        "diabetes": {
            "sugar": 1.67                  # 1일 기준: 5
        },
        "hypertension": {
            "sodium": 766.67,              # 1일 기준: 2300
            "potassium_min": 1166.67,      # > 1166.67mg (1일 기준: 3500)
            "fat_ratio": 0.25              # 총 열량의 25% 이하 (비율이므로 그대로 유지)
        }
    }

    # 2. 우선순위 맵 (낮을수록 높음)
    priority_map = {
        "allergy": 1,
        "kidneydisease": 2,
        "diabetes": 3,
        "hypertension": 4
    }

    # 3. 사용자가 가진 질환 필터링 및 우선순위 정렬
    # 예: user_diseases = {"diabetes": 1, "kidneydisease": 1}
    active_diseases = [d for d, active in user_diseases.items() if active == 1]
    sorted_diseases = sorted(active_diseases, key=lambda x: priority_map.get(x, 99))

    # 4. Final Profile 생성 (Priority-Merger)
    final_profile = {
        "user_id": user_id,
        "restricted_ingredients": []
    }

    for disease in sorted_diseases:
        # 신장병의 경우 세부 단계(투석 여부)에 따른 분기 처리가 필요할 수 있습니다.
        # 여기서는 예시로 pre_dialysis를 기본값으로 사용합니다.
        lookup_key = "kidneydisease_pre_dialysis" if disease == "kidneydisease" else disease
        thresholds = disease_thresholds.get(lookup_key, {})

        for nutrient, value in thresholds.items():
            # 알러지 유발 물질 문자열 처리
            if nutrient == "restricted_ingredients":
                # 중복 없이 추가
                final_profile["restricted_ingredients"] = list(set(final_profile["restricted_ingredients"] + value))

            # 성분 임계값 처리: 이미 등록된 성분은 무시 (우선순위 보호)
            elif nutrient not in final_profile:
                final_profile[nutrient] = value

    return final_profile

# --- 실행 예시 ---
user_id_a = "patient_A"
user_weight_a = 70 # kg
user_diseases_a = {
    "diabetes": 1,
    "hypertension": 0,
    "kidneydisease": 1,
    "allergy": 0
}

profile = generate_final_profile(user_id_a, user_diseases_a, user_weight_a)

import json
print(json.dumps(profile, indent=4, ensure_ascii=False))

# 식품 성분 매핑 테이블 정의

# final_profile 키 : 식품 DB 컬럼명 매핑
FOOD_DB_MAPPER = {
    "calories" : "에너지(kcal)",
    "sodium" : "나트륨(mg)",
    "carbohydrate" : "탄수화물(g)",
    "sugar" : "당류(g)",
    "fat": "지방(g)",
    "trans fat" : "트랜스지방(g)",
    "saturated fat" : "포화지방(g)",
    "cholesterol" : "콜레스테롤(mg)",
    "protein" : "단백질(g)",
    "phosphorus" : "인(mg)",
    "calcium" : "칼슘(mg)",
    "potassium" : "칼륨(mg)"
    # 식품표시 의무대상 및 disease_thresholds에서 사용된 성분을 전부 매핑함
    # 왼쪽 칼럼 출처: disease_thresholds
    # 오른쪽 칼럼 출: 식품의약품 안전처에서 제공하는 "20251229_음식DB 19495건"
}

"""#🧾 JSON 데이터"""

products = {
    "0": {
        "product_id": "201905000000",
        "name": "설화눈꽃팝김부각스낵",
        "category": "과자",
        "ingredients": ["찹쌀", "김", "참깨", "옥수수기름", "양파", "무", "대파", "천일염", "마늘", "새우", "멸치", "다시마", "건표고버섯", "둥굴레", "감초", "정제수"],
        "allergy": "없음",
        "trace": "null",
        "calories": 150, "sodium": 180, "carbohydrate": 20, "sugar": 1,
        "fat": 7, "trans_fat": 0, "saturated_fat": 1.2, "cholesterol": 5,
        "protein": 2, "phosphorus": 45, "calcium": 30, "potassium": 120
    },
    "1": {
        "product_id": "201804000001",
        "name": "설화눈꽃팝김부각스낵 아몬드맛",
        "category": "과자",
        "ingredients": ["찹쌀", "김", "참깨", "아몬드", "양파", "무", "천일염", "새우", "멸치", "다시마", "정제수"],
        "allergy": "아몬드",
        "trace": "",
        "calories": 170, "sodium": 160, "carbohydrate": 18, "sugar": 1,
        "fat": 10, "trans_fat": 0, "saturated_fat": 1.0, "cholesterol": 3,
        "protein": 4, "phosphorus": 80, "calcium": 50, "potassium": 200
    },
    "2": {
        "product_id": "201804000002",
        "name": "고들빼기김치",
        "category": "김치류",
        "ingredients": ["고들빼기", "멸치액", "염장새우", "양파", "혼합간장", "고춧가루", "마늘", "참깨", "물엿", "배즙", "당근"],
        "allergy": "새우,대두,밀",
        "trace": "밀, 땅콩, 복숭아, 토마토, 호두, 아황산류 혼입 가능",
        "calories": 45, "sodium": 850, "carbohydrate": 8, "sugar": 4,
        "fat": 0.5, "trans_fat": 0, "saturated_fat": 0.1, "cholesterol": 2,
        "protein": 2, "phosphorus": 35, "calcium": 40, "potassium": 320
    },
    "3": {
        "product_id": "199504000000",
        "name": "해태 허니버터칩",
        "category": "과자",
        "ingredients": ["감자", "혼합식용유", "허니버터맛시즈닝", "탈지분유(우유)", "버터혼합분말(대두)", "아카시아꿀", "고메버터(밀)"],
        "allergy": "알수없음",
        "trace": "null",
        "calories": 345, "sodium": 350, "carbohydrate": 30, "sugar": 7,
        "fat": 23, "trans_fat": 0.1, "saturated_fat": 8, "cholesterol": 10,
        "protein": 3, "phosphorus": 70, "calcium": 25, "potassium": 450
    },
    "4": {
        "product_id": "201405000000",
        "name": "헬로버블 라이스퍼프 양파맛",
        "ingredients": ["현미", "어니언시즈닝", "정백당", "리치버터분말", "양파분", "합성향료", "백미", "옥수수과립"],
        "allergy": "알수없음",
        "trace": "돼지고기, 땅콩, 복숭아, 아황산류, 호두 혼입 가능",
        "calories": 120, "sodium": 110, "carbohydrate": 22, "sugar": 3,
        "fat": 2.5, "trans_fat": 0, "saturated_fat": 0.5, "cholesterol": 0,
        "protein": 2, "phosphorus": 55, "calcium": 15, "potassium": 90
    },
    "5": {
        "product_id": "201105000000",
        "name": "두마리목장 콜비치즈",
        "ingredients": ["원유(국산)99.9%", "우유응고효소", "유산균", "식염", "안나토색소"],
        "allergy": "우유함유",
        "trace": "null",
        "calories": 115, "sodium": 190, "carbohydrate": 1, "sugar": 0.5,
        "fat": 9, "trans_fat": 0.3, "saturated_fat": 6, "cholesterol": 30,
        "protein": 7, "phosphorus": 140, "calcium": 210, "potassium": 25
    },
    "6": {
        "product_id": "201105000001",
        "name": "양반 바삭 튀김가루",
        "ingredients": ["밀가루", "변성전분", "베이킹파우더", "정제소금", "양파분말", "옥수수가루"],
        "allergy": "밀",
        "trace": "null",
        "calories": 350, "sodium": 650, "carbohydrate": 78, "sugar": 2,
        "fat": 1.2, "trans_fat": 0, "saturated_fat": 0.3, "cholesterol": 0,
        "protein": 7, "phosphorus": 95, "calcium": 20, "potassium": 110
    },
    "7": {
        "product_id": "201104000001",
        "name": "돈목살훈제바베큐스테이크",
        "ingredients": ["돼지고기 96.68%", "스모크시즈닝", "분리대두단백", "토마토케찹", "아질산나트륨"],
        "allergy": "돼지고기,밀,우유,대두,쇠고기,토마토 함유",
        "trace": "null",
        "calories": 280, "sodium": 720, "carbohydrate": 5, "sugar": 2,
        "fat": 20, "trans_fat": 0, "saturated_fat": 7, "cholesterol": 65,
        "protein": 19, "phosphorus": 180, "calcium": 15, "potassium": 310
    },
    "8": {
        "product_id": "201104000002",
        "name": "태양초 고추장 골드",
        "ingredients": ["고춧가루", "물엿", "소맥분(밀)", "혼합양념", "밀쌀", "정제소금", "정백당"],
        "allergy": "알수없음",
        "trace": "null",
        "calories": 210, "sodium": 2400, "carbohydrate": 48, "sugar": 25,
        "fat": 1, "trans_fat": 0, "saturated_fat": 0.2, "cholesterol": 0,
        "protein": 4, "phosphorus": 90, "calcium": 35, "potassium": 450
    },
    "9": {
        "product_id": "201104000003",
        "name": "환타지 믹스너트",
        "ingredients": ["커피땅콩", "화이트볼", "찹쌀땅콩", "튀김땅콩", "로스티드피너츠", "바나나칩", "볶음아몬드", "꿀땅콩"],
        "allergy": "알수없음",
        "trace": "null",
        "calories": 520, "sodium": 280, "carbohydrate": 45, "sugar": 18,
        "fat": 34, "trans_fat": 0, "saturated_fat": 9, "cholesterol": 0,
        "protein": 14, "phosphorus": 310, "calcium": 75, "potassium": 580
    }
}





# 테스트용 유저 파이널프로필 (당뇨 + 신장병 환자 가정)
final_profiles = {
    "0": { # 당뇨 + 우유/땅콩 알러지
        "restricted_ingredients": ["우유", "땅콩"],
        "sugar": 5.0
    },
    "1": { # 고혈압 + 새우 알러지
        "restricted_ingredients": ["새우"],
        "sodium": 2300.0,
        "potassium": 3500.0,
        "fat_ratio": 0.25
    },
    "2": { # 투석 전 신장질환 (70kg 기준)
        "restricted_ingredients": [],
        "protein": 42.0,  # 0.6 * 70
        "sodium": 2300.0,
        "phosphorus": 1000.0,
        "calcium": 1000.0
    },
    "3": { # 투석 중 신장질환 + 밀 알러지
        "restricted_ingredients": ["밀"],
        "protein": 84.0,  # 1.2 * 70
        "sodium": 2300.0,
        "potassium": 2000.0,
        "phosphorus": 1000.0
    },
    "4": { # 당뇨 + 고혈압 복합 (가장 흔한 케이스)
        "restricted_ingredients": [],
        "sugar": 5.0,
        "sodium": 2300.0,
        "potassium": 3500.0,
        "fat_ratio": 0.25
    },
    "5": { # 복합 알러지 (유제품, 계란, 견과류)
        "restricted_ingredients": ["우유", "계란", "견과류"],

    },
    "6": { # 당뇨 + 투석 전 신장질환 + 대두 알러지
        "restricted_ingredients": ["대두"],
        "sugar": 5.0,
        "protein": 42.0,
        "sodium": 2300.0,
        "phosphorus": 1000.0
    },
    "7": { # 고혈압 + 생선/조개류 알러지
        "restricted_ingredients": ["고등어", "조개"],
        "sodium": 2300.0,
        "potassium": 3500.0,
        "fat_ratio": 0.25
    },
    "user_8": { # 모든 질환 복합 (최악의 시나리오 - 고위험군)
        "restricted_ingredients": ["땅콩", "밀"],
        "sugar": 5.0,
        "protein": 42.0,
        "sodium": 2300.0,
        "potassium": 2000.0, # 신장질환 기준 적용
        "phosphorus": 1000.0,
        "fat_ratio": 0.25
    },
    "9": { # 고령자 타겟 (고혈압 + 투석 중 신장질환)
        "restricted_ingredients": [],
        "protein": 84.0,
        "sodium": 2300.0,
        "potassium": 2000.0,
        "phosphorus": 1000.0,
        "fat_ratio": 0.25
    }
}

allergy_substitution_rules = {
    "description": "식약처 고시 22종 알레르기 유발 물질별 대체 식재료 추천 가이드",
    "rules": [
      {
        "category": "난류",
        "items": ["계란", "메추리알", "오리알"],
        "substitutes": ["두부", "병아리콩 거품(아쿠아파바)", "치아씨드 페이스트", "강낭콩"],
        "usage_tip": "베이킹 시 계란의 결합력은 아쿠아파바나 바나나로 대체 가능합니다."
      },
      {
        "category": "우유",
        "items": ["우유", "산양유", "원유", "탈지분유", "환원유", "환원무지방우유", "가공유"],
        "substitutes": ["두유", "아몬드유", "오트유", "쌀음료", "코코넛밀크"],
        "usage_tip": "크리미한 질감을 원할 경우 코코넛밀크나 캐슈넛 밀크가 적합합니다."
      },
      {
        "category": "메밀",
        "items": ["메밀"],
        "substitutes": ["쌀", "밀", "감자 전분", "고구마 전분"],
        "usage_tip": "면 요리 시 쌀면이나 전분 함량이 높은 면으로 쫄깃함을 대체합니다."
      },
      {
        "category": "땅콩",
        "items": ["땅콩"],
        "substitutes": ["해바라기씨", "호박씨", "캐슈넛(견과류 알러지 없을 시)", "병아리콩"],
        "usage_tip": "고소한 맛은 볶은 씨앗류나 콩류로 대체 가능합니다."
      },
      {
        "category": "대두",
        "items": ["대두"],
        "substitutes": ["완두콩", "병아리콩", "코코넛 아미노스(간장 대체)", "퀴노아"],
        "usage_tip": "간장 대신 코코넛 아미노스를 사용하면 대두 없이 감칠맛을 낼 수 있습니다."
      },
      {
        "category": "밀",
        "items": ["밀"],
        "substitutes": ["쌀가루", "귀리가루", "타피오카 가루", "메밀가루(메밀 알러지 없을 시)"],
        "usage_tip": "글루텐 프리 가루 믹스를 사용하여 점성을 조절하세요."
      },
      {
        "category": "잣",
        "items": ["잣"],
        "substitutes": ["해바라기씨", "호박씨", "마카다미아"],
        "usage_tip": "바질 페스토 등 소스 제작 시 씨앗류로 대체 가능합니다."
      },
      {
        "category": "호두",
        "items": ["호두"],
        "substitutes": ["피칸", "호박씨", "볶은 귀리"],
        "usage_tip": "식감과 풍미가 유사한 피칸이 가장 좋은 대안입니다."
      },
      {
        "category": "게/새우",
        "items": ["게", "새우"],
        "substitutes": ["흰살 생선", "버섯(킹오이스터)", "두부"],
        "usage_tip": "탱글한 식감은 버섯이나 어묵(성분 확인 필수)으로 대체합니다."
      },
      {
        "category": "돼지고기/쇠고기/닭고기",
        "items": ["돼지고기", "쇠고기", "닭고기"],
        "substitutes": ["콩고기", "템페", "버섯류", "생선"],
        "usage_tip": "단백질원은 식물성 단백질이나 대체육으로 보충합니다."
      },
      {
        "category": "복숭아/토마토",
        "items": ["복숭아", "토마토"],
        "substitutes": ["사과", "자두(복숭아 대용)", "빨간 파프리카(토마토 대용)"],
        "usage_tip": "토마토 소스의 색감과 산미는 파프리카와 식초 조합으로 흉내 낼 수 있습니다."
      },
      {
        "category": "아황산류",
        "items": ["아황산류(산화방지제)"],
        "substitutes": ["천연 발효 식초", "레몬즙", "생과일"],
        "usage_tip": "가공식품보다는 신선 식품 위주의 선택이 필수적입니다."
      },
      {
        "category": "조개류/굴/전복/홍합",
        "items": ["조개류", "굴", "전복", "홍합"],
        "substitutes": ["다시마", "표고버섯", "멸치(생선 알러지 없을 시)"],
        "usage_tip": "국물 요리의 감칠맛은 해조류와 버섯으로 충분히 낼 수 있습니다."
      },
      {
        "category": "오징어",
        "items": ["오징어"],
        "substitutes": ["문어(연체류 알러지 확인)", "버섯", "곤약"],
        "usage_tip": "쫄깃한 식감은 데친 곤약이나 버섯 기둥으로 대체 가능합니다."
      }
    ]
  }

"""#🤖 에이전트 개요

START: 유저가 [장바구니 담기] 버튼을 클릭함

##1️⃣ Node 1 (Orch-01): Eligibility Checking & Routing (Conditional Edge)

###1. 유저가 질병을 보유하고 있는가?
*@USER-Agent 호출
* IN: USER-01의 Profile Retrieval
* Logic : PASS or WARN

      disease = diabetes + hypertension + kidneydisease + allergy

          ** PASS: disease = 0    -> end
          ** WARN: disease >= 1   -> 2. 이동


###2. 식품에 유관 성분이 있는가?
*@CHAT-Agent 호출
* IN: CHAT-01의 Evidence Generation
* logic : PASS or WARN

          ** PASS: 부적합성분 없음    -> end,
          ** WARN: 부적합성분 있음    -> to_chat, to_reco

* next: 판정결과에 따라 다른 에이전트 및 tool 호출, 상품특성 JSON 전달

#
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
#

##2️⃣ Node 2 (User-01): Profile Retrieval

유저프로필을 조회하여 건강정보 확인 및 페르소나를 JSON 출력
* MVP: ?user_id?, weight, diabetes, hypertension, kidneydisease, allergy
* Post-MVP: height, activity_level, persona(FK, Post-MVP DB)



### 참고) final_profile DB
Node2(User-02) + priority_map + 유관성분 임계값&문자열 필터링
* 미리 생성해서 DB에 저장된 상태

Logic :
* 임계값 기반 필터링

      diabetes: (-)당(<5g)
                (+)식이섬유(>=14g/1,000kcal)

      hypertension: (-)나트륨(<2,300mg/day),
                    (-)칼륨 > 3500mg
                    (-)총 지방 < 하루 총 열량의 20-25% 이하

      kidneydisease:  CKD 3-5단계 (투석 전, 당뇨 없음)
                      (-)단백질 kg당 0.55-0.60g/kg/일
                      (-)나트륨 2.3g 미만
                      (-)인 800-1,000 mg/일
                      (-)칼슘 800-1,000mg/일
                      (-)25-35 kcal/kg/일

                      CKD 5단계 (투석)
                      (+)단백질 1.0-1.2g/kg/일
                      (-)나트륨 2.3g 미만
                      (-)칼륨 2,000/일로 제한
                      (-)인 800-1,000 mg/일
                      (-)칼슘 800-1,000mg/일
                      (-)25-35 kcal/kg/일
      
      (POST-MVP에서는 (+) 성분 섭취시 긍정피드백을 주는것도 고려)

* 문자열 기반 필터링

      allergy: 우유, 달걀, 땅콩, 견과류, 콩, 밀, 생선, 갑각류 어패류
      원재료 포함성분 및 교차오염성분

* 우선순위 순으로

      priority_map = { allergy: 1, kidneydisease: 2, diabetes : 3, hypertension: 4 }

          질병 우선순위에 따른 필터링성분 및 임계값을 먼저 호출.
          그 다음 순위 질병의 필터링성분을 호출
          -> 이미 호출된 필터링성분은 새로 호출하지 않음
          Priority-Merger -> 질병 우선순위에 따라 Final_Profile 생성

      final_profile = {
          user_id: ,
          성분1: 성분1함량,
          성분2: 성분2함량,
          알러지: 알러젠
          ...

#
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
#

##3️⃣ Node 3 (Chat-01): Evidence Generation

식품성분과 질환 가이드라인을 대조하여 근거기반 적합성 판별후 *JSON 출력*
* IN: final_profile DB, product DB, disease RAG?

      *final_profile DB:
      *product DB: product_id, name, category, brand
                -> 성분함량체크 및 상품 조회 맥락 유지
      *disease RAG: 질병유관 성분 및 성분 가이드(함량)
                -> 식품 성분 적합성
* logic : 질환별 성분 필터링 (simple check)

* 판단결과 예시 ----> **JSON 기반으로 변경 필요

      Scenario : 🚫 영양 성분 초과 (Nutrient Violation)
        - 최종 판정: [WARN]
        - 위반 알러지: []
        - 위반 영양소: ['sodium', 'sugar']
        - 상세 리포트:
          ✅ PROTEIN: 실제 15.0 / 기준 40.0
          🚩 SODIUM: 실제 3000.0 / 기준 2300.0
          🚩 SUGAR: 실제 10.0 / 기준 5.0





위 정보를 받아서 reco로 넘김

##4️⃣ Node 4 (Reco-01): Vector DB Search & Recommendation

* 상품특성 JSON을 받아서 유사한 상품 조회 및 추천

##4️⃣ Node 4-1 (sub-Reco-01): Vector DB Search & Recommendation

방식1: 레코에서 준 30-50개 정도의 상품중에서 roles.py 로 3개를 추천
방식2: 레코에서는 3개만 주고 그 3개 상품의 조회맥락과 식품성분이 유저에게 맞는지 판단

##5️⃣ Node 5 (Resp-01):

#🤖 에이전트

####라이브러리
"""

from dataclasses import dataclass
from typing_extensions import TypedDict

from langchain_core.runnables import RunnableConfig
from langgraph.graph import StateGraph
from langgraph.runtime import Runtime

from langgraph.graph import START
from langgraph.graph import END

#orchagnet = RouterLogic(router_llm) - llm 사용의 합리성 검토 후 비사용

useragent = ProfileRetrieval(retrieval_llm)

chatagent = EvidenceGeneration(generation_llm)

recoagent = Recommendation(recommendation_llm)

subsagent = ProductSubstitution(substitution_llm)

respagent = ResponseGeneration(response_llm)

"""#### 에이전트별 모델 설정 모음"""

# main.py 또는 graph.py 상단
from langchain_openai import ChatOpenAI

# 라우터 로직에서는 llm 사용 안하기로
#router_llm = ChatOpenAI(
#    model="gpt-4o",
#    temperature=0,   # 판단의 일관성을 위해 0으로 설정
#    api_key="sk-..." # (환경변수로 관리)
#)



retrieval_llm = ChatOpenAI(model="gpt-4o", temperature=0)
generate_llm = ChatOpenAI(model="gpt-4o", temperature=0)
recommendation_llm = ChatOpenAI(model="gpt-4o", temperature=0)

"""#### 오케스트레이션 에이전트"""

class RouterLogic:
    def __init__(self):
        #
        pass

    def run(self, state: overallState) -> str:
        print("\n⚙️ [Orch-Agent] 규칙 기반 경로 판단 중...")

        # 1. 데이터 추출
        u_profile = state.get("user_profile", {})
        
        # chat_agent에서 설정된 분석 결과 추출
        any_exceed = state.get("any_exceed", False)
        any_allergen = state.get("any_allergen", False)

        # 체크할 플래그 리스트
        flag_keys = ["diabetes_flag", "hypertension_flag", "kidneydisease_flag", "allergy_flag"]

        # 플래그 값 추출 (dict.get을 사용하여 키가 없는 경우 None 처리)
        flags = [u_profile.get(key) for key in flag_keys]

        # --- [조건분기 시작] ---

        # 규칙 1: 필수 플래그 중 하나라도 누락(None)된 경우
        if any(f is None for f in flags):
            reason = "필수 건강 정보(Flags) 일부 누락"
            return self._log_and_return("user_agent", reason)

        # 규칙 2: WARN 판정 - any_exceed 또는 any_allergen이 true인 경우
        # chat_agent가 실행되고 피드백 루프로 돌아왔을 때 이 조건이 활성화됨
        if any_exceed or any_allergen:
            reason = f"위험 성분 감지 (영양성분 초과: {any_exceed}, 알러지: {any_allergen})"
            return self._log_and_return("reco_agent", reason)

        # 규칙 3: 플래그가 모두 존재할 때 합계 계산
        # 0과 1로 구성되어 있다고 가정 (True/False여도 sum 가능)
        flag_sum = sum(int(f) for f in flags)

        if flag_sum >= 1:
            return self._log_and_return("chat_agent", f"질환/알러지 보유 ({flag_sum}단계)")
        else:
            return self._log_and_return("end", "질환/알러지 없음 (정상)")

    def _log_and_return(self, next_step, reason):
        print(f"👉 판단 결과: {next_step} (이유: {reason})")
        return next_step





"""#### 유저 에이전트"""

from typing import List, Dict, Any, TypedDict
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_core.runnables import RunnableConfig



# 1. LLM 구조화 출력을 위한 Pydantic 모델
class HealthAnalysis(BaseModel):
    """질병 정보에 기반한 식이 가이드 및 주의 성분"""
    guidelines: List[str] = Field(
        ...,
        description="환자의 질병 정보를 바탕으로 한 구체적인 식단 가이드라인 3~5가지"
    )
    target_ingredients: List[str] = Field(
        ...,
        description="해당 질병 보유자가 피해야 하거나 주의해야 할 핵심 성분명 리스트 (예: 나트륨, 당류, 포화지방)"
    )

# 2. User Agent 클래스 (ProfileRetrieval)
class ProfileRetrieval:
    def __init__(self, model):
        """
        Args:
            model: 구조화된 출력을 지원하는 LLM 객체 (예: ChatOpenAI)
        """
        self.llm = model
        # LLM이 Pydantic 모델에 맞춰 답하도록 설정
        self.analysis_chain = self.llm.with_structured_output(HealthAnalysis)

    def _fetch_profile_from_backend(self, user_id: str) -> Dict[str, Any]:
        """
        [Mock API] user_id를 'Key'로 사용하여 백엔드 DB에서 유저 정보를 조회함.
        실제로는 requests.get(f"api/user/{user_id}") 형태가 됨.
        """
        print(f"📡 [User-Agent] 백엔드 조회 중... (Target ID: {user_id})")

        # 임시 DB (Mock Data)
        mock_db = {
            "user_001": {
                "name": "김철수",
                "diabetes": 1,        # 당뇨 있음
                "hypertension": 1,    # 고혈압 있음
                "kidneydisease": 0,
                "allergy": 0
            },
            "user_002": {
                "name": "이영희",
                "diabetes": 0,
                "hypertension": 0,
                "kidneydisease": 1,   # 신장질환 있음
                "allergy": 1          # 알러지 있음
            }
        }

        # DB에 없으면 기본값 반환
        return mock_db.get(user_id, {
            "name": "Unknown", "diabetes": 0, "hypertension": 0, "kidneydisease": 0, "allergy": 0
        })

    def run(self, state: OverallState, config: RunnableConfig = None) -> Dict[str, Any]:
        """LangGraph 노드 실행 함수"""

        # 1. State에서 user_id 꺼내기 (이미 있는 정보 활용)
        current_user_id = state.get("user_id")

        # 2. 백엔드 API를 통해 상세 프로필(질병 유무) 가져오기
        user_profile = self._fetch_profile_from_backend(current_user_id)

        # 3. LLM에게 분석 요청 (0/1 데이터를 텍스트 가이드로 변환)
        #    프롬프트에 질병 정보를 요약해서 전달
        health_summary = (
            f"당뇨: {'있음' if user_profile['diabetes'] else '없음'}, "
            f"고혈압: {'있음' if user_profile['hypertension'] else '없음'}, "
            f"신장질환: {'있음' if user_profile['kidneydisease'] else '없음'}, "
            f"알러지: {'있음' if user_profile['allergy'] else '없음'}"
        )

        system_msg = "당신은 임상 영양사입니다. 환자의 질병 정보를 바탕으로 식단 가이드와 주의 성분을 추출하세요."

        # LLM 호출 (구조화된 출력 반환)
        analysis_result: HealthAnalysis = self.analysis_chain.invoke([
            SystemMessage(content=system_msg),
            HumanMessage(content=f"환자 정보: {health_summary}")
        ])

        print(f"✅ [User-Agent] 분석 완료: {analysis_result.target_ingredients}")

        # 4. State 업데이트 (스키마에 맞춰서 반환)
        return {
            # (1) 백엔드에서 가져온 Raw Data
            "name": user_profile["name"],
            "diabetes": user_profile["diabetes_flag"],
            "hypertension": user_profile["hypertension_flag"],
            "kidneydisease": user_profile["kidneydisease_flag"],
            "allergy": user_profile["allergy_flag"],

            "diabetes_type": user_profile["diabetes_detail"],
            "hypertension_type": user_profile["hypertension_detail"],
            "kidneydisease_type": user_profile["kidneydisease_detail"],
            "allergy_list": user_profile["allergy_list"],

            "final_profile": user_profile, # 임계값

            # (4) 흐름 제어 (오케스트레이터에게 턴을 넘김)
            "next_step": "orch_agent"
        }

# --- 사용 예시 ---

# 1. LLM 정의 (앞서 만든 router_llm과 같은 모델 사용 가능)
# from langchain_openai import ChatOpenAI
# retrieval_llm = ChatOpenAI(model="gpt-4o", temperature=0)

# 2. 클래스 인스턴스 생성
useragent = ProfileRetrieval(retrieval_llm)

# 3. LangGraph에 노드 추가 시
# workflow.add_node("user_agent", useragent.run)




"""#### 챗 애널리시스 에이전트"""


import json

class EvidenceGeneration1:
    def __init__(self, model, tokenizer, final_profiles=None, products=None):
        self.llm = model # For LangChain compatibility if needed, though not used in generate_prompt current logic
        self.model = model
        self.tokenizer = tokenizer
        # 데이터를 클래스 속성으로 저장
        self.final_profiles = final_profiles if final_profiles is not None else {}
        self.products = products if products is not None else {}

# 1. 당뇨, 고혈압, 신부전 분석
    def evaluate_threshold1(self, final_profile_key, product_key) -> overallState:
        """
        영양성분 임계값 초과 여부를 분석하여 overallState 형식으로 반환합니다.
        """
        profile = self.final_profiles.get(str(final_profile_key), {})
        product = self.products.get(str(product_key), {})

        # 디버깅: 데이터 확인
        print(f"\n=== 디버깅 정보 ===")
        print(f"final_profile_key: {final_profile_key} (type: {type(final_profile_key)})")
        print(f"product_key: {product_key} (type: {type(product_key)})")
        print(f"profile 데이터: {profile}")
        print(f"product 데이터: {product}")
        print(f"self.final_profiles의 키들: {list(self.final_profiles.keys())}")
        print(f"self.products의 키들: {list(self.products.keys())}")

        # 1. overallState 구조에 맞게 결과 객체 초기화
        state: overallState = {
            "any_exceed": False,
            "exceeded_nutrients": []
        }

        # 2. 분석 제외 키 설정
        exclude_keys = ['user_id', 'restricted_ingredients']
        target_nutrients = [k for k in profile.keys() if k not in exclude_keys]
        
        print(f"target_nutrients (분석 대상): {target_nutrients}")

        # 3. 영양성분 전수 조사
        for nutrient in target_nutrients:
            limit = profile[nutrient]
            
            # 컬럼 이름이 동일하므로 그대로 사용 (fat_ratio만 예외)
            actual = product.get(nutrient, 0)
            
            print(f"\n[체크] {nutrient}: 기준={limit}, 실제={actual}")

            # fat_ratio는 비율 계산 필요 (지방 칼로리 / 총 칼로리)
            if nutrient == 'fat_ratio':
                total_calories = product.get('calories', 0)
                fat_calories = product.get('fat', 0) * 9  # 지방 1g = 9kcal
                if total_calories > 0:
                    actual_ratio = fat_calories / total_calories
                    print(f"  지방 비율 계산: {fat_calories}kcal / {total_calories}kcal = {actual_ratio:.3f}")
                    if actual_ratio > limit:
                        print(f"  ❌ 비율 초과: {actual_ratio:.3f} > {limit}")
                        state["any_exceed"] = True
                        state["exceeded_nutrients"].append(nutrient)
                    else:
                        print(f"  ✅ 비율 적정")
            # 일반적인 경우: 기준 초과 여부 확인 (Exceed)
            else:
                if actual > limit:
                    print(f"  ❌ 기준 초과: {actual} > {limit}")
                    state["any_exceed"] = True
                    state["exceeded_nutrients"].append(nutrient)
                else:
                    print(f"  ✅ 기준 이하")
        
        print(f"\n=== 최종 결과 ===")
        print(f"any_exceed: {state['any_exceed']}")
        print(f"exceeded_nutrients: {state['exceeded_nutrients']}")
        print(f"==================\n")

        return state


# 2. 알러지 분석


    def generate_allergy_prompt1(self, product_key, final_profile_key, tone_key=None, max_new_tokens=512):
        """
        정의된 모듈의 Key 값을 받아 최적화된 시스템 프롬프트를 생성합니다.
        """
        # 2.1. 클래스 외부 변수 데이터 가져오기 (데이터가 없을 경우를 대비해 get 사용)
        p = products.get(str(product_key))
        f = final_profiles.get(str(final_profile_key))
        sub_rules = allergy_substitution_rules

        # 2.2. 예외 처리: 데이터가 없는 경우 None이 아닌 명확한 문자열 반환
        if not p or not f:
            return f"Error: 정보를 찾을 수 없습니다. (Product: {product_key}, Profile: {final_profile_key})"

        # 2.3. 시스템 프롬프트
        system_msg = f"""당신은 식품 성분 및 화학 분석 전문가입니다.
        주어진 원재료 리스트를 분석하여 사용자의 제한 사항('restricted_ingredients')과 대조하고 솔루션을 제공하세요.

        ### [Layer 1] 식약처 22종 마스터 리스트 기준
        분석 기준은 대한민국 식약처 고시 알레르기 유발 물질 22종입니다.

        ### [Layer 2] 원재료 추론 및 매핑 규칙
        1. 성분명에 직접적인 이름이 없더라도 '핵심 기원(Source) 물질'을 식별합니다. (예: '카제인나트륨' -> '우유')
        2. 대체 식재료는 다음 가이드를 참조하십시오:
        {sub_rules.get('rules', [])}

        ### [Layer 3] 분석 가이드라인
        - **Priority**: 1순위 알러지 차단 / 2순위 질환 영양 수치 충족 여부.
        - **Severity Level**: Critical(함유), Warning(교차 오염 가능성), Safe(무관) 분류.
        - ** 알러지를 유발할 수 있는 모든 원재료를 표시하세요.
        - ** 다른사람에게 알러지 가능성 있다 라는 식의 표현 사용하지 마세요.
        - ** 추론 규칙을 드러내지 마세요.
        - ** 반드시 아래의 json 형태로만 출력하세요. 주어진 json 컬럼 외에는 답변하지 마세요.


        ### [출력 형식]
        {{
          "ingredient_analysis": [
            {{
              "detected_ingredient": "성분명",
              "derived_from": "기원물질(22종 기준)",
              "substitute": "추천 대체재",
              "is_allergen": true
            }}
          ],
          "safety_summary": "최종 섭취 가능 여부 및 주의사항",
        }}

        [예시] few-shot
        {{
          "ingredient_analysis": [
            {{
              "detected_ingredient": "새우",
              "derived_from": "새우",
              "substitute": "흰살 생선, 버섯(킹오이스터), 두부",
              "is_allergen": false
            }}
          ],
          "safety_summary": "이 제품은 사용자의 알러지 항목인 우유와 땅콩을 포함하고 있지 않으므로 안전하게 섭취 가능합니다.",
        }}



        """

        # 2.4. 유저 프롬프트
        # 시스템 메시지의 변동성을 최소화하기 위해 동적데이터를 유저 메시지로 몰아넣습니다.
        user_msg = f"""
        [상품 정보]
        - 상품명: {p.get('name', '알 수 없음')}
        - 원재료: {p.get('ingerdients', [])}
        - 제조사 주의사항: {p.get('allergy', '없음')} / {p.get('trace', '없음')}

        [유저 프로필]
        - 제한 성분: {f.get('restricted_ingredients')}
        """



        messages = [
                    {"role": "system", "content": system_msg},
                    {"role": "user", "content": user_msg}
        ]



        # 3. llm 토크나이징
        # chat template 적용 → BatchEncoding 반환
        inputs = self.tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt"
        ).to(self.model.device)

        attention_mask = inputs.get("attention_mask", None)
        if attention_mask is not None:
           attention_mask = attention_mask.to(self.model.device)

        with torch.no_grad():
             outputs = self.model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=attention_mask,
                max_new_tokens=max_new_tokens,
                temperature=0.1,
                top_p=0.9,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                eos_token_id=self.tokenizer.eos_token_id
        )

        # 프롬프트 길이 이후만 디코딩
        # 3.1. 질문의 길이를 잽니다.
        prompt_length = inputs["input_ids"].shape[-1]

        # 3.2. 슬라이싱: 전체 결과에서 10번째 이후부터만 가져옵니다.
        generated_ids = outputs[0][prompt_length:]

        # 3.3. 답변만 남은 generated_ids를 글자로 바꿉니다.
        raw_response = self.tokenizer.decode(generated_ids, skip_special_tokens=True)
        
        # 디버깅: 원본 응답 출력
        print(f"\n=== 원본 LLM 응답 ===")
        print(raw_response)
        print(f"===================\n")

        # overallState 초기화
        state: overallState = {
            "any_allergen": False,
            "substitute": []
        }

        try:
            # JSON 추출: 마크다운 코드 블록 제거 및 JSON 부분만 추출
            response_text = raw_response.strip()
            
            # 마크다운 코드 블록 제거 (```json ... ``` 형태)
            if response_text.startswith("```"):
                # 첫 번째 줄 제거
                lines = response_text.split('\n')
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                response_text = '\n'.join(lines)
            
            # 첫 번째 { 부터 마지막 } 까지 추출
            start_idx = response_text.find('{')
            end_idx = response_text.rfind('}')
            
            if start_idx == -1 or end_idx == -1:
                print("Error: JSON 형식을 찾을 수 없습니다.")
                return state
            
            json_text = response_text[start_idx:end_idx+1]
            
            # 트레일링 콤마 제거 (JSON 파싱 에러의 흔한 원인)
            import re
            json_text = re.sub(r',\s*}', '}', json_text)
            json_text = re.sub(r',\s*]', ']', json_text)
            
            print(f"\n=== 추출된 JSON ===")
            print(json_text)
            print(f"===================\n")
            
            # LLM의 출력이 JSON 형식이므로 파싱 시도
            data = json.loads(json_text)

            analysis = data.get("ingredient_analysis", [])

            # any_allergen 추출: 분석 결과 중 하나라도 true가 있으면 true
            state["any_allergen"] = any(item.get("is_allergen", False) for item in analysis)

            # substitute 추출: is_allergen이 true인 항목의 대체재만 수집 (중복 제거)
            sub_list = []
            for item in analysis:
                # is_allergen이 true인 항목만 처리
                if item.get("is_allergen", False):
                    sub = item.get("substitute", "")
                    if sub and sub != "없음":
                        # "생선, 두부" 처럼 문자열로 올 경우를 대비해 분리
                        sub_list.extend([s.strip() for s in sub.split(',')])

            state["substitute"] = list(set(sub_list))  # 중복 제거
            
            print(f"\n=== 최종 파싱 결과 ===")
            print(f"any_allergen: {state['any_allergen']}")
            print(f"substitute: {state['substitute']}")
            print(f"===================\n")

        except json.JSONDecodeError as e:
            print(f"Parsing Error: {e}")
            print(f"문제가 된 텍스트 (앞 200자): {json_text[:200] if 'json_text' in locals() else raw_response[:200]}")
            # 실패 시 기본 state 반환

        return state








"""식품의 영양성분 정보가 없음

#### 레커멘데이션 에이전트

#### 섭스티튜션 에이전트 : Tool calling

조건식으로 분기하는거랑
아무거나 치면 네가 뭐가 필요한지 판단해서 calling해서 써 가 다름
오케스트레이션이 알아서 툴 호출해서 쓰게하려면 tool calling

tool calling 기능을 지원하는 모델이 있음
아닌 경우 ollama 래핑 사용가능
gpt api 쓰면 정확하고 쉽고 빠르게 잘 됨
local model (ex) qwen -

입력된 정보에 대해 가치판단을 하거나 예측을 해서 동작해야함

tool calling 컨셉:
llm이 하기 어려운 동작들 -명확한 수식을 통한 계산이라던가 외부 호출이라던가 그거를 더 잘하는 도구를 호출하는것
"""

from langchain_core.tools import tool

@tool
def multiply(a: int, b: int) -> int:
  """Mutifly a and b"""
  return a * b

  #나중에 구현

"""# 🔄 LangGraph

### NODE 기능 정의/선언
"""

## 워크플로우 정의 및 노드&엣지 등록

from langgraph.graph import StateGraph

workflow = StateGraph(overallState)

# orchestrator 로직 (policy.py 의 RouterLogic 인스턴스가 orchagent라고 가정)
# 코드 상단에서 인스턴스가 없다면 아래와 같이 매핑합니다.
# workflow.add_node("orch_agent", orchagent.run) 
# 현재 노트북 코드에서는 orchagent 변수 할당이 주석처리되어 있으므로, 
# 기존 초기화된 RouterLogic() 사용
orchagent = RouterLogic()

workflow.add_node("orch_agent", orchagent.run)

workflow.add_node("user_agent", useragent.run)
workflow.add_node("chat_agent", chatagent.evaluate_threshold)

# user 님 요청사항: reco_agent 의 독자적 state 유지를 위해 중간 브릿지 래퍼 사용 
# 이 코드는 recoagent 가 State 보존을 어떻게 할지에 따라 변경할 수 있으나,
# 지금은 recoagent.run (또는 정의된 메인 진입점)을 호출한다고 가정합니다.
# (만약 reco_node 함수가 별도로 정의되어 있다면 해당 함수를 사용하세요)
workflow.add_node("reco_agent", recoagent.run if hasattr(recoagent, 'run') else lambda state: state)

workflow.add_node("sub_reco_agent", subsagent.run if hasattr(subsagent, 'run') else lambda state: state)
workflow.add_node("resp_agent", respagent.run if hasattr(respagent, 'run') else lambda state: state)

workflow.add_edge(START, "orch_agent")
workflow.add_edge("orch_agent", "user_agent")
workflow.add_edge("user_agent", "orch_agent")

workflow.add_edge("orch_agent", "chat_agent")
workflow.add_edge("chat_agent", "orch_agent")

workflow.add_edge("chat_agent", "reco_agent")

workflow.add_edge("orch_agent", "reco_agent")
workflow.add_edge("reco_agent", "sub_reco_agent")
workflow.add_edge("sub_reco_agent", "reco_agent")
workflow.add_edge("sub_reco_agent", "resp_agent")




workflow.add_conditional_edges(
    "orch_agent",               # 시작 노드
    lambda x: x.get("next_step", "end"),   # 라우터의 결과값(next_step)을 읽어서
    {                           # 실제 이동할 노드 매핑
        "user_agent": "user_agent",
        "chat_agent": "chat_agent",
        "reco_agent": "reco_agent",
        "sub_reco_agent": "sub_reco_agent",
        "resp_agent": "resp_agent",
        "end": END
    }
)




workflow.add_edge("orch_agent", END)
workflow.add_edge("resp_agent", END)


from typing import TypedDict, List








app = workflow.compile()

"""# 🔍 시각화"""

from IPython.display import Image, display

# workflow.compile()을 마친 app 객체를 사용합니다.
try:
    display(Image(app.get_graph().draw_mermaid_png()))
except Exception:
    # 환경에 따라 추가 라이브러리(pyppeteer 등)가 필요할 수 있습니다.
    print("그래프를 시각화할 수 없습니다.")

"""# 🎶 아키텍쳐 연결, 최종출력, 동작확인"""

# 초기 입력값 (빈 값으로 시작해도 됨)
initial_input = {"user_id": "start_user"}

# 그래프 실행
final_state = app.invoke(initial_input)

# 최종 결과 확인
print("\n--- 최종 상태 결과 ---")
print(final_state)

