"""create nutrients table

Revision ID: 5d17c68389df
Revises: 8471f31fcc9a
Create Date: 2026-02-20 18:16:11.295237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d17c68389df'
down_revision: Union[str, Sequence[str], None] = '8471f31fcc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('nutri_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_mandatory_display', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diabetes_risk', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hypertension_risk', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_glycemic_factor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kidneydisease_risk', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('nutri_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrients')
    # ### end Alembic commands ###
