"""create products table

Revision ID: 7f669d0dd39f
Revises: 962ad7ad2028
Create Date: 2026-02-20 17:45:34.219575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f669d0dd39f'
down_revision: Union[str, Sequence[str], None] = '962ad7ad2028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rawmtrl', sa.Text(), nullable=True),
    sa.Column('allergymtrl', sa.Text(), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('ash_g', sa.Integer(), nullable=True),
    sa.Column('carb_g', sa.Integer(), nullable=True),
    sa.Column('sugar_g', sa.Integer(), nullable=True),
    sa.Column('sodium_mg', sa.Integer(), nullable=True),
    sa.Column('cholesterol_mg', sa.Integer(), nullable=True),
    sa.Column('sat_fat_g', sa.Integer(), nullable=True),
    sa.Column('trans_fat_g', sa.Integer(), nullable=True),
    sa.Column('nutrient_basis_g', sa.Integer(), nullable=True),
    sa.Column('serving_ref_g', sa.Integer(), nullable=True),
    sa.Column('food_weight_g', sa.Integer(), nullable=True),
    sa.Column('gi', sa.Integer(), nullable=True),
    sa.Column('gl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('brand', name='uq_products_brand')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
