"""create user_health_profile table

Revision ID: 9f7ed843fa58
Revises: 3385df4a9f92
Create Date: 2026-02-20 15:55:52.526613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7ed843fa58'
down_revision: Union[str, Sequence[str], None] = '3385df4a9f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_health_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_of_steps', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('diabetes', sa.Enum('type1', 'type2', 'pre_type1', 'pre_type2', 'na', name='diabetes_enum'), nullable=True),
    sa.Column('hypertension', sa.Enum('prehypertension', 'stage1', 'stage2', 'na', name='hypertension_enum'), nullable=True),
    sa.Column('kidneydisease', sa.Enum('chronic_kidney_disease', 'kidney_failure', 'kidney_stones', 'proteinuria', 'nephrotic_syndrome', 'na', name='kidney_disease_enum'), nullable=True),
    sa.Column('allergy', sa.Enum('egg', 'milk', 'peanut', 'tree_nut', 'shellfish', 'fish', 'wheat', 'soy', 'peach', 'na', name='allergy_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('favorite', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_health_profile')
    # ### end Alembic commands ###
